import generated from "./locales.generated.json";

export const languages = [
  ["system", "Follow system"], ["ar", "العربية"], ["pt-BR", "Português (Brasil)"], ["zh-CN", "简体中文"],
  ["cs", "Čeština"], ["da", "Dansk"], ["nl", "Nederlands"], ["en", "English"], ["fi", "Suomi"],
  ["fr", "Français"], ["de", "Deutsch"], ["it", "Italiano"], ["ja", "日本語"], ["ko", "한국어"],
  ["nb", "Norsk bokmål"], ["pl", "Polski"], ["ru", "Русский"], ["es", "Español"], ["sv", "Svenska"],
  ["tr", "Türkçe"], ["uk", "Українська"], ["vi", "Tiếng Việt"], ["be", "Беларуская"],
  ["ro", "Română"], ["bg", "Български"],
] as const;

const keys = ["Board", "Workers", "Properties", "Import tasks", "Settings", "Project board", "New task", "Appearance and language", "Language", "Color scheme", "Time zone", "Board columns", "AI workflow", "Human workflow", "Custom", "Move up", "Move down", "Delete column", "New column name", "Add column", "Web and MCP", "Board refresh (seconds)", "Worker refresh (seconds)", "Save settings", "Saving…", "Dark", "Light", "Black", "Ubuntu", "Windows", "System time zone", "Follow system"] as const;
type Key = typeof keys[number];
const rows: Record<string, string> = {
  ru: "Доска|Воркеры|Свойства|Импорт задач|Настройки|Доска проекта|Новая задача|Вид и язык|Язык|Цветовая схема|Часовой пояс|Колонки доски|Рабочий процесс AI|Рабочий процесс человека|Пользовательская|Выше|Ниже|Удалить колонку|Название новой колонки|Добавить колонку|Веб и MCP|Обновление доски (сек.)|Обновление воркеров (сек.)|Сохранить настройки|Сохранение…|Тёмная|Светлая|Чёрная|Ubuntu|Windows|Системный часовой пояс|Как в системе",
  be: "Дошка|Воркеры|Уласцівасці|Імпарт задач|Налады|Дошка праекта|Новая задача|Выгляд і мова|Мова|Колеравая схема|Часавы пояс|Калонкі дошкі|Працэс AI|Працэс чалавека|Уласная|Вышэй|Ніжэй|Выдаліць калонку|Назва новай калонкі|Дадаць калонку|Вэб і MCP|Абнаўленне дошкі (сек.)|Абнаўленне воркераў (сек.)|Захаваць налады|Захаванне…|Цёмная|Светлая|Чорная|Ubuntu|Windows|Сістэмны часавы пояс|Як у сістэме",
  uk: "Дошка|Воркери|Властивості|Імпорт завдань|Налаштування|Дошка проєкту|Нове завдання|Вигляд і мова|Мова|Колірна схема|Часовий пояс|Колонки дошки|Процес AI|Процес людини|Власна|Вище|Нижче|Видалити колонку|Назва нової колонки|Додати колонку|Веб і MCP|Оновлення дошки (с)|Оновлення воркерів (с)|Зберегти налаштування|Збереження…|Темна|Світла|Чорна|Ubuntu|Windows|Системний часовий пояс|Як у системі",
  ro: "Panou|Lucrători|Proprietăți|Importă sarcini|Setări|Panoul proiectului|Sarcină nouă|Aspect și limbă|Limbă|Temă de culori|Fus orar|Coloanele panoului|Flux AI|Flux uman|Personalizată|Mută sus|Mută jos|Șterge coloana|Numele coloanei noi|Adaugă coloană|Web și MCP|Actualizare panou (secunde)|Actualizare lucrători (secunde)|Salvează setările|Se salvează…|Întunecată|Luminoasă|Neagră|Ubuntu|Windows|Fusul orar al sistemului|Conform sistemului",
  bg: "Табло|Работници|Свойства|Импорт на задачи|Настройки|Табло на проекта|Нова задача|Външен вид и език|Език|Цветова схема|Часова зона|Колони на таблото|Работен процес на AI|Работен процес на човек|Потребителска|Нагоре|Надолу|Изтрий колона|Име на нова колона|Добави колона|Уеб и MCP|Обновяване на таблото (сек.)|Обновяване на работниците (сек.)|Запази настройките|Запазване…|Тъмна|Светла|Черна|Ubuntu|Windows|Системна часова зона|Според системата",
  ar: "اللوحة|العاملون|الخصائص|استيراد المهام|الإعدادات|لوحة المشروع|مهمة جديدة|المظهر واللغة|اللغة|نظام الألوان|المنطقة الزمنية|أعمدة اللوحة|سير عمل الذكاء الاصطناعي|سير العمل البشري|مخصص|تحريك لأعلى|تحريك لأسفل|حذف العمود|اسم العمود الجديد|إضافة عمود|الويب و MCP|تحديث اللوحة (ثوان)|تحديث العاملين (ثوان)|حفظ الإعدادات|جارٍ الحفظ…|داكن|فاتح|أسود|Ubuntu|Windows|المنطقة الزمنية للنظام|حسب النظام",
  "pt-BR": "Quadro|Trabalhadores|Propriedades|Importar tarefas|Configurações|Quadro do projeto|Nova tarefa|Aparência e idioma|Idioma|Esquema de cores|Fuso horário|Colunas do quadro|Fluxo da IA|Fluxo humano|Personalizada|Mover para cima|Mover para baixo|Excluir coluna|Nome da nova coluna|Adicionar coluna|Web e MCP|Atualização do quadro (s)|Atualização dos trabalhadores (s)|Salvar configurações|Salvando…|Escuro|Claro|Preto|Ubuntu|Windows|Fuso horário do sistema|Seguir sistema",
  "zh-CN": "看板|工作者|属性|导入任务|设置|项目看板|新任务|外观和语言|语言|配色方案|时区|看板列|AI 工作流程|人工工作流程|自定义|上移|下移|删除列|新列名称|添加列|Web 与 MCP|看板刷新（秒）|工作者刷新（秒）|保存设置|正在保存…|深色|浅色|黑色|Ubuntu|Windows|系统时区|跟随系统",
  cs: "Tabule|Pracovníci|Vlastnosti|Import úkolů|Nastavení|Tabule projektu|Nový úkol|Vzhled a jazyk|Jazyk|Barevné schéma|Časové pásmo|Sloupce tabule|Pracovní postup AI|Lidský postup|Vlastní|Posunout nahoru|Posunout dolů|Smazat sloupec|Název nového sloupce|Přidat sloupec|Web a MCP|Obnovení tabule (s)|Obnovení pracovníků (s)|Uložit nastavení|Ukládání…|Tmavý|Světlý|Černý|Ubuntu|Windows|Systémové časové pásmo|Podle systému",
  da: "Tavle|Arbejdere|Egenskaber|Importer opgaver|Indstillinger|Projekttavle|Ny opgave|Udseende og sprog|Sprog|Farvetema|Tidszone|Tavlekolonner|AI arbejdsgang|Menneskelig arbejdsgang|Brugerdefineret|Flyt op|Flyt ned|Slet kolonne|Navn på ny kolonne|Tilføj kolonne|Web og MCP|Opdater tavle (sek.)|Opdater arbejdere (sek.)|Gem indstillinger|Gemmer…|Mørk|Lys|Sort|Ubuntu|Windows|Systemets tidszone|Følg system",
  nl: "Bord|Werkers|Eigenschappen|Taken importeren|Instellingen|Projectbord|Nieuwe taak|Uiterlijk en taal|Taal|Kleurenschema|Tijdzone|Bordkolommen|AI-werkstroom|Menselijke werkstroom|Aangepast|Omhoog|Omlaag|Kolom verwijderen|Naam nieuwe kolom|Kolom toevoegen|Web en MCP|Bord vernieuwen (sec.)|Werkers vernieuwen (sec.)|Instellingen opslaan|Opslaan…|Donker|Licht|Zwart|Ubuntu|Windows|Systeemtijdzone|Systeem volgen",
  fi: "Taulu|Työntekijät|Ominaisuudet|Tuo tehtäviä|Asetukset|Projektitaulu|Uusi tehtävä|Ulkoasu ja kieli|Kieli|Värimalli|Aikavyöhyke|Taulun sarakkeet|AI-työnkulku|Ihmisen työnkulku|Mukautettu|Siirrä ylös|Siirrä alas|Poista sarake|Uuden sarakkeen nimi|Lisää sarake|Web ja MCP|Taulun päivitys (s)|Työntekijöiden päivitys (s)|Tallenna asetukset|Tallennetaan…|Tumma|Vaalea|Musta|Ubuntu|Windows|Järjestelmän aikavyöhyke|Seuraa järjestelmää",
  fr: "Tableau|Agents|Propriétés|Importer des tâches|Paramètres|Tableau du projet|Nouvelle tâche|Apparence et langue|Langue|Palette de couleurs|Fuseau horaire|Colonnes du tableau|Flux de l’IA|Flux humain|Personnalisée|Monter|Descendre|Supprimer la colonne|Nom de la nouvelle colonne|Ajouter une colonne|Web et MCP|Actualisation du tableau (s)|Actualisation des agents (s)|Enregistrer les paramètres|Enregistrement…|Sombre|Clair|Noir|Ubuntu|Windows|Fuseau horaire système|Suivre le système",
  de: "Board|Worker|Eigenschaften|Aufgaben importieren|Einstellungen|Projektboard|Neue Aufgabe|Aussehen und Sprache|Sprache|Farbschema|Zeitzone|Board-Spalten|KI-Arbeitsablauf|Menschlicher Ablauf|Benutzerdefiniert|Nach oben|Nach unten|Spalte löschen|Name der neuen Spalte|Spalte hinzufügen|Web und MCP|Board-Aktualisierung (s)|Worker-Aktualisierung (s)|Einstellungen speichern|Speichern…|Dunkel|Hell|Schwarz|Ubuntu|Windows|Systemzeitzone|System folgen",
  it: "Bacheca|Worker|Proprietà|Importa attività|Impostazioni|Bacheca del progetto|Nuova attività|Aspetto e lingua|Lingua|Schema colori|Fuso orario|Colonne della bacheca|Flusso AI|Flusso umano|Personalizzata|Sposta su|Sposta giù|Elimina colonna|Nome nuova colonna|Aggiungi colonna|Web e MCP|Aggiorna bacheca (s)|Aggiorna worker (s)|Salva impostazioni|Salvataggio…|Scuro|Chiaro|Nero|Ubuntu|Windows|Fuso orario di sistema|Segui sistema",
  ja: "ボード|ワーカー|プロパティ|タスクをインポート|設定|プロジェクトボード|新しいタスク|外観と言語|言語|配色|タイムゾーン|ボードの列|AI ワークフロー|人間のワークフロー|カスタム|上へ|下へ|列を削除|新しい列名|列を追加|Web と MCP|ボード更新（秒）|ワーカー更新（秒）|設定を保存|保存中…|ダーク|ライト|ブラック|Ubuntu|Windows|システムのタイムゾーン|システムに従う",
  ko: "보드|워커|속성|작업 가져오기|설정|프로젝트 보드|새 작업|모양 및 언어|언어|색 구성표|시간대|보드 열|AI 작업 흐름|사람 작업 흐름|사용자 지정|위로|아래로|열 삭제|새 열 이름|열 추가|웹 및 MCP|보드 새로고침(초)|워커 새로고침(초)|설정 저장|저장 중…|어둡게|밝게|검정|Ubuntu|Windows|시스템 시간대|시스템 설정 따르기",
  nb: "Tavle|Arbeidere|Egenskaper|Importer oppgaver|Innstillinger|Prosjekttavle|Ny oppgave|Utseende og språk|Språk|Fargetema|Tidssone|Tavlekolonner|AI-arbeidsflyt|Menneskelig arbeidsflyt|Egendefinert|Flytt opp|Flytt ned|Slett kolonne|Navn på ny kolonne|Legg til kolonne|Web og MCP|Oppdater tavle (s)|Oppdater arbeidere (s)|Lagre innstillinger|Lagrer…|Mørk|Lys|Svart|Ubuntu|Windows|Systemets tidssone|Følg systemet",
  pl: "Tablica|Pracownicy|Właściwości|Importuj zadania|Ustawienia|Tablica projektu|Nowe zadanie|Wygląd i język|Język|Schemat kolorów|Strefa czasowa|Kolumny tablicy|Przepływ AI|Przepływ człowieka|Własna|Przesuń w górę|Przesuń w dół|Usuń kolumnę|Nazwa nowej kolumny|Dodaj kolumnę|Web i MCP|Odświeżanie tablicy (s)|Odświeżanie pracowników (s)|Zapisz ustawienia|Zapisywanie…|Ciemny|Jasny|Czarny|Ubuntu|Windows|Systemowa strefa czasowa|Zgodnie z systemem",
  es: "Tablero|Trabajadores|Propiedades|Importar tareas|Configuración|Tablero del proyecto|Nueva tarea|Apariencia e idioma|Idioma|Esquema de colores|Zona horaria|Columnas del tablero|Flujo de IA|Flujo humano|Personalizada|Subir|Bajar|Eliminar columna|Nombre de la nueva columna|Agregar columna|Web y MCP|Actualizar tablero (s)|Actualizar trabajadores (s)|Guardar configuración|Guardando…|Oscuro|Claro|Negro|Ubuntu|Windows|Zona horaria del sistema|Seguir sistema",
  sv: "Tavla|Arbetare|Egenskaper|Importera uppgifter|Inställningar|Projekttavla|Ny uppgift|Utseende och språk|Språk|Färgschema|Tidszon|Tavlans kolumner|AI-arbetsflöde|Mänskligt arbetsflöde|Anpassad|Flytta upp|Flytta ned|Ta bort kolumn|Namn på ny kolumn|Lägg till kolumn|Webb och MCP|Uppdatera tavla (s)|Uppdatera arbetare (s)|Spara inställningar|Sparar…|Mörk|Ljus|Svart|Ubuntu|Windows|Systemets tidszon|Följ systemet",
  tr: "Pano|Çalışanlar|Özellikler|Görevleri içe aktar|Ayarlar|Proje panosu|Yeni görev|Görünüm ve dil|Dil|Renk şeması|Saat dilimi|Pano sütunları|Yapay zeka iş akışı|İnsan iş akışı|Özel|Yukarı taşı|Aşağı taşı|Sütunu sil|Yeni sütun adı|Sütun ekle|Web ve MCP|Pano yenileme (sn)|Çalışan yenileme (sn)|Ayarları kaydet|Kaydediliyor…|Koyu|Açık|Siyah|Ubuntu|Windows|Sistem saat dilimi|Sistemi izle",
  vi: "Bảng|Nhân viên|Thuộc tính|Nhập tác vụ|Cài đặt|Bảng dự án|Tác vụ mới|Giao diện và ngôn ngữ|Ngôn ngữ|Bảng màu|Múi giờ|Cột bảng|Quy trình AI|Quy trình người dùng|Tùy chỉnh|Di chuyển lên|Di chuyển xuống|Xóa cột|Tên cột mới|Thêm cột|Web và MCP|Làm mới bảng (giây)|Làm mới nhân viên (giây)|Lưu cài đặt|Đang lưu…|Tối|Sáng|Đen|Ubuntu|Windows|Múi giờ hệ thống|Theo hệ thống",
};

const russianExtra: Record<string, string> = {
  "Task saved": "Задача сохранена", "Property saved": "Свойство сохранено", "Worker saved": "Воркер сохранён", "Save failed": "Не удалось сохранить",
  "Placeholder": "Подсказка в поле", "Regex": "Регулярное выражение", "Default value": "Значение по умолчанию",
  "All projects": "Все проекты", "Workspace": "Рабочее пространство", "Filters": "Фильтры", "Fit all columns": "Уместить все колонки", "Wide columns": "Широкие колонки", "Registered workers": "Зарегистрированные воркеры", "Add worker": "Добавить воркера", "Add property": "Добавить свойство", "Task properties": "Свойства задач", "Create task": "Создать задачу", "Edit task": "Редактировать задачу", "Edit worker": "Редактировать воркера", "Title": "Название", "Description": "Описание", "State": "Этап", "Priority": "Приоритет", "Responsible": "Ответственный", "Testing mode": "Режим тестирования", "Dependencies": "Зависимости", "AI test instructions": "Инструкции для AI тестирования", "Human test instructions": "Инструкции для ручного тестирования", "Name": "Имя", "Slug": "Идентификатор", "Kind": "Тип", "Enabled": "Включён", "Capability preset": "Профиль возможностей", "Advanced: capabilities JSON": "Дополнительно: возможности JSON", "Cancel": "Отмена", "Save": "Сохранить", "Search": "Поиск", "Open project": "Открыть проект", "Projects": "Проекты", "Complete": "Готово", "Backlog": "Очередь", "Features": "Задачи", "In progress": "В работе", "Testing": "Тестирование", "Verification": "Проверка", "Offline": "Не в сети", "Active": "Активен", "Delete": "Удалить", "Import": "Импорт", "Settings saved": "Настройки сохранены",
  "AI workflow columns are fixed. Custom columns are human-only; moving a task there places it in Backlog for the AI workflow.": "Этапы AI фиксированы. Пользовательские колонки доступны только человеку; перенос задачи туда возвращает её в Backlog для процесса AI.",
  "Deleting a custom column returns its tasks to Backlog when you save.": "После сохранения задачи удалённой колонки вернутся в Backlog.",
  "The web server listens on 127.0.0.1:7337 by default. Change the address with --addr when starting agentboard open or serve; restart is required.": "По умолчанию веб-сервер доступен на 127.0.0.1:7337. Адрес меняется флагом --addr при запуске agentboard open или serve; потребуется перезапуск.",
  "Each worker uses its own MCP command. Open a worker to copy its client configuration and check the connection.": "У каждого воркера своя команда MCP. Откройте воркера, чтобы скопировать конфигурацию клиента и проверить подключение.",
  "Board layout": "Режим отображения доски", "All priority": "Любой приоритет", "All testing": "Любое тестирование", "All responsible": "Все ответственные", "All origins": "Все источники", "Drop tasks here": "Перетащите задачи сюда", "MCP diagnostics": "Диагностика MCP", "No description": "Без описания", "No matching tasks": "Подходящих задач нет", "unassigned": "Не назначено", "Disabled": "Отключён", "Never": "Никогда",
};
const localeOverrides: Record<string, Record<string, string>> = {
  fr: { Backlog: "À faire", Features: "Fonctionnalités", "Drag task": "Déplacer la tâche", "Open task": "Ouvrir la tâche" },
};
const translations = Object.fromEntries(Object.entries(rows).map(([language, row]) => [language, Object.fromEntries(row.split("|").map((value, i) => [keys[i], value]))])) as Record<string, Record<Key, string>>;
let activeLanguage = "en";
export function setLanguage(language: string) {
  const resolved = language === "system" ? navigator.language : language;
  activeLanguage = rows[resolved] ? resolved : (resolved.split("-")[0] in rows ? resolved.split("-")[0] : "en");
  document.documentElement.lang = activeLanguage;
  document.documentElement.dir = activeLanguage === "ar" ? "rtl" : "ltr";
}
export function t(text: string) {
  const manual = translations[activeLanguage]?.[text as Key] || (activeLanguage === "ru" ? russianExtra[text] : undefined) || localeOverrides[activeLanguage]?.[text];
  if (manual) return manual;
  if (text === "Slug") return "Slug";
  if (text === "git") return "Git";
  if (text === "comfyui") return "ComfyUI";
  return (generated as Record<string, Record<string, string>>)[activeLanguage]?.[text] || text;
}
